### ISSUE TITLE
realpath: command not found

### ISSUE THREAD

**Issue by haghshenas** [sfu-compbio/colormap#3]
realpath command is deprecated and cannot be found on some systems.
In the bash script, try using a different command like readlink for getting the absolute path.

**Comment by Mattstorey** [comment]
I solved this, in ubuntu 14.04.4 trusty, with: apt-get realpath and ran the script again.

**Comment by haghshenas** [comment]
[Fixed](https://github.com/sfu-compbio/colormap/commit/f5d4c9c003b0b743a1f4657d8651f4b0c515c1ff) by using **readlink** instead of **realpath**.
