### ISSUE TITLE
Output files

### ISSUE THREAD

**Issue by Mattstorey** [sfu-compbio/colormap#4]
Hi, 

Install was a piece of cake (thanks) and I ran the script on my data sets with no troubles! 
However, the output was not what I expected. The run returned; <outPrefix>_.iter1.fasta, <outPrefix>_.2iter.fasta and <outPrefix>_uncorr.fasta.
Are any of these the corrected files?

Cheers.

**Comment by haghshenas** [comment]
Hi there,

Yes, the file containing corrected reads are stored in **iter2.fasta**.
In fact, _iter1.fasta_ contains reads corrected by a single round of SP algorithm and _iter2.fasta_ contains reads corrected by a second round of SP algorithm.

**Comment by Mattstorey** [comment]
Great. Thanks for the reply. Is there a smart way to compare the corrected
reads to the uncorrected reads. Even just a subset of these. I'm interested
to see how much correction has occurred?

Cheers,
Matt.

**Comment by haghshenas** [comment]
One way to compare corrected and uncorrected reads (specially for bacterial genomes) is to map them to the reference genome and calculate the identity/accuracy of the mappings. 
Alternatively, if you want to analyze a small subset of reads [LRCstats](https://github.com/thefantasticdron/lrcstats) might be a good option.
